#!/bin/sh
if expr match "$0" ".*/lh\-" > /dev/null ; then
  echo "cookies - LostHeros CLI"
  echo ""
fi

CJ=".cookie.jar"
WD="$LH_MULTIUSER"

if [ ! "$1" = "" ]; then
  WD="$1"
fi

if [ ! "$WD" = "" ]; then
  CJ="$WD/$CJ"
fi

if [ ! -e "$CJ" ]; then
  echo "no cookies: $CJ"
  exit 1
fi

echo "# Domain\t\tMatch\tPath\tSecure\tExpires\t\tName\t\tValue"
echo "# "
cat "$CJ"
echo ""
echo "# date --date='@1546037741'"
