#!/bin/sh
if expr match "$0" ".*/lh\-" > /dev/null ; then
  echo "logout - LostHeros CLI"
  echo ""
fi

CJ=".cookie.jar"
WD="$LH_MULTIUSER"

if [ ! "$WD" = "" ]; then
  CJ="$WD/$CJ"
  WD="/$WD"
fi

if [ "$1" = "-h" -o "$1" = "--help" -o "$1" = "" -o "$2" = "" ]; then
  echo "losthero: logout confirm logout"
  echo " cookies: delete '$CJ'"
  echo "    note: not mandatory"
  exit 1
fi

SV="`grep --no-messages "^server=" .$WD/auto.set | cut -d = --fields=2`"

if [ "$SV" = "" ]; then
  SV="http://webgame.losthero.com/"
fi

if [ -e "$CJ" ]; then
if which curl > /dev/null ; then
  curl --silent --cookie "$CJ" "${SV}logout.php" > /dev/null
  EC=$?
  if [ $EC -gt 0 ]; then
    echo "logout error: curl: $SV"
    grep --max-count=1 "^$EC" .$BD/errors.curl
  fi
elif which wget > /dev/null ; then
  wget --quiet --unlink --load-cookies -O /dev/null "$CJ" "${SV}logout.php"
  EC=$?
#  rm -f logout.php
  if [ $EC -gt 0 ]; then
    echo "logout error: wget: $SV"
    grep --max-count=1 "^$EC" .$BD/errors.wget
  fi
else
  echo "logout error: need 'curl' or 'wget'"
  echo ""
  exit 2
fi
  rm -f "$CJ"
  echo "logged out"
else
  echo "not logged in"
fi

echo "" > ./.multiuser
export LH_MULTIUSER=""

exit 0
