#!/bin/sh

WD="$LH_MULTIUSER"

if [ ! "$WD" = "" ]; then
  WD="/$WD"
fi

printf "show "
if [ "$1" = "" ]; then
  echo "(xtx.)_what_ - LostHeros CLI"
  echo ""
  cd .$WD/
  ls xtx.*
else
  GW="`echo "$1" | sed -e 's/\xtx.//g'`"
  echo "$GW" | sed -r 's/\b(.)/\u\1/g' | xargs printf "%s - LostHeros CLI\n"
  echo ""
  cat ".$WD/xtx.$GW"
fi
