#!/bin/sh

WD="$LH_MULTIUSER"

if [ ! "$WD" = "" ]; then
  WD="/$WD"
fi

if [ "$1" = "" ]; then
  echo "value (val.)_what_ - LostHeros CLI"
  echo ""
  cd .$WD/
  ls val.*
else
  GW=`echo "$1" | sed 's/\val.//g'`
  printf "%s=" "$GW"
  cat ".$WD/val.$GW"
fi

exit 0
